#ifndef NETWORKING_CORE_H
#define NETWORKING_CORE_H


enum PacketType {
    PACKET_PLAYER_UPDATE = 0,
    PACKET_PLAYER_ID,
    PACKET_MOVE,
    PACKET_CHUNK_UPDATE,
    PACKET_INIT_INVENTORY_ELEMENT,
};

#endif
